# Function to return empty data frame with all features to be used in model
createFrame <- function() {

  # Creating dataframe of the variables to use in model
  data.features <- data.frame(listing_id = character(0), 
                              bathrooms = numeric(0), 
                              bedrooms = numeric(0),
                              created = as.POSIXct(character()), 
                              yday = numeric(0),
                              month = numeric(0),
                              mday = numeric(0),
                              wday = numeric(0),
                              hour = numeric(0),
                              nphotos = numeric(0),
                              ndescription = numeric(0),
                              manager_id = character(0),
                              managerNoLis = numeric(0),
                              managerLoPer = numeric(0),
                              managerMePer = numeric(0),
                              managerHiPer = numeric(0),
                              managerSkill = numeric(0),
                              latitude = numeric(0),
                              longitude = numeric(0),
                              price = numeric(0),
                              interest = character(0),
                              elevator = character(0),
                              wood = character(0),
                              pets = character(0),
                              noPets = character(0),
                              doorman = character(0),
                              dishwasher = character(0),
                              laundryUnit = character(0),
                              laundryBuilding = character(0),
                              prewar = character(0),
                              roofdeck = character(0),
                              outdoorPublic = character(0),
                              outdoorPrivate = character(0),
                              diningroom = character(0),
                              internet = character(0),
                              balcony = character(0),
                              pool = character(0),
                              noFee = character(0),
                              fitness = character(0),
                              newConstruction = character(0),
                              exclusive = character(0),
                              highCeilings = character(0),
                              renovated = character(0),
                              park = character(0),
                              livein = character(0),
                              lounge = character(0),
                              closet= character(0),
                              playroom = character(0),
                              ac= character(0),
                              wheelchair= character(0),
                              fireplace = character(0),
                              loft = character(0),
                              simplex = character(0),
                              lowrise = character(0),
                              highrise = character(0),
                              furnished = character(0),
                              duplex = character(0),
                              green = character(0),
                              storage = character(0),
                              ss = character(0),
                              light = character(0),
                              misc = character(0),
                              subway = character(0),
                              shortTerm = character(0),
                              view = character(0),
                              postwar= character(0), 
                              countFeatures = numeric(0), stringsAsFactors=FALSE)
  
  return(data.features)
}